    - name: Install Nginx
      apt:
        name: nginx
        state: present



    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Install PHP and required extensions
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php7.4-fpm
        - php7.4-mbstring
        - php7.4-xml
        - php7.4-mysql
        - php-curl
        - zip 
        - unzip

    - name: Copy PHP-FPM configuration
      template:
         src: templates/php-fpm.conf.j2
         dest: /etc/php/7.4/fpm/php-fpm.conf


    - name: Start PHP-FPM service
      service:
        name: php7.4-fpm
        state: started
        enabled: yes   


    - name: Download Composer installation
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Move  composer-setup.php  to  /usr/local/bin folder
      command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  

  

